---
title: "Quelques opérations faites sur la base céréales"
author: "ONANENA AMANA Jeanne De La Flèche"
date: "2024-03-16"
output: pdf_document

editor_options:
  markdown:
    wrap: 72
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
# RECODONS LA VARAIBLE TYPE DE CEREALES 

# Importons la base 

options(repos = "https://cloud.r-project.org/")
install.packages("readxl")

library(haven)

cereales <- read_dta("C:/Users/Mitson Informatique/Documents/ISEP2/Semestre 2/Traitement statistiques avec R/ISEP2_Cours_R_2024/Bases/cereales.dta")

View(cereales)
colnames(cereales)[4:14] <- c("AutresCereales","Qtty_cons",
                              "Unite_cons","Taille_cons",
                              "AutoCons","AutresProv",
                              "DernierAchat","Qtty_achat",
                              "Unite_achat","Taille_achat",
                              "Value_achat")
# Recodage (Je vais regrouper les differents types de cereales representés par la variable cereales__id en 4 differentes categories )

names(cereales)
unique(cereales$cereales__id)

library(dplyr)

vecteur_recodage <- case_when(
  cereales$cereales__id %in% c(1,2,3,4,5,6,7,9,10,11,12) ~ "Céréales de base",
  cereales$cereales__id %in% c(13,14,15,16,17,18,19,20) ~ "Produits dérivés des céréales",
  cereales$cereales__id %in% c(21,22,23,24,25,26) ~ "Produits de boulangerie",
  cereales$cereales__id == 169 ~ "Céréales du petit déjeuner",
  TRUE ~ NA_character_  # Pour les valeurs non prévues, NA
)

cereales <- cereales %>%
  mutate(cereale_recodée = vecteur_recodage)

#DECOUPAGE EN CLASSE D'une cereale et une unité standard qu'on aura identifié  (PETITE CONSOMMATION (inferieur à 10kg), MOYENNE(inf à 20 ) ET GRANDE ((sup à 20)))
# Regroupons en classe les differentes consommations 

library(dplyr)

cereales <- cereales %>%
  mutate (Quantite_achetee_recodée = case_when (
    Qtty_achat < 5 ~ "Faible quantité achetée", 
    Qtty_achat >= 5 & Qtty_achat < 10 ~ "Moyenne quantité achetée",
    Qtty_achat >= 10 ~ "Forte quantité achetée",
    TRUE ~ NA_character_
  ))

cereales <- cereales %>%
  mutate (Quantite_consommée_recodée = case_when (
    Qtty_cons < 5 ~ "Faible quantité consommée", 
    Qtty_cons >= 5 & Qtty_cons < 10 ~ "Moyenne quantité consommée",
    Qtty_cons >= 10 ~ "Forte quantité consommée",
    TRUE ~ NA_character_
  ))

library(readxl)  
table_conversion <- read_xlsx("C:/Users/Mitson Informatique/Documents/ISEP2/Semestre 2/Traitement statistiques avec R/ISEP2_Cours_R_2024/Bases/Table de conversion phase 2.xlsx")

View(table_conversion)

#IMPORTER LA TABLE DES CONVERSIONS , IDENTIFIER LES VARIABLES DE MERGE ET FAIRE DES MANIPULATIONS POUR MERGER CA AVEC LA BASE CEREALES

colnames(table_conversion)[colnames(table_conversion) == "produitID"] <- "cereales_id"

dataframe_fusion <- merge(table_conversion, cereales, 
                          by = c("cereales__id" = "produitID",
                             "Unite_cons" = "uniteID",
                             "Taille_cons" = "tailleID"))


#CREER DES VARIABLES FACTEURS

# Liste des variables à transformer en facteurs

variables_a_transformer <- c("AutoCons", "Qtty_achat", "Qtty_cons", "Value_achat", "DernierAchat")

# Boucle à travers les variables pour les transformer en facteurs
for (variable in variables_a_transformer) {
  cereales[[variable]] <- as_factor(cereales[[variable]])
}
```

```{r}
#Exportation de la base
write.csv(cereales, file = "base_exportée.csv")
```

```{r}
#donne les valeurs manquantes par variable
data.frame(variables=colnames(cereales),'valeurs manquantes'=apply(cereales,MARGIN = 2, function(x) sum(is.na(x))))

#le plus optimal
data.frame('valeurs manquantes'=apply(cereales,MARGIN = 2, function(x) sum(is.na(x))))
#pour voir l'aide de apply on fait base::apply

```


```{r}
#IMPORTATION DE LA BASE
library(readxl)
Table_de_conversion_phase_2 <- read_excel(
  "C:/Users/Mitson Informatique/Documents/ISEP2/Semestre 2/Traitement statistiques avec R/ISEP2_Cours_R_2024/Bases/Table de conversion phase 2.xlsx")

Table_de_conversion_phase_2$...8 <- NULL
Table_de_conversion_phase_2$...9 <- NULL
View(Table_de_conversion_phase_2)

colnames(Table_de_conversion_phase_2)[1:6] <- c("cereales__id","Nom_Prod",
                                                "Unite_cons","Nom_Unite",
                                                "Taille_cons","Nom_Taille")

merge <- merge(cereales, Table_de_conversion_phase_2, 
               by = c("cereales__id", "Unite_cons", "Taille_cons"), all.x = TRUE)
```

